"""add original_url to file_map

Revision ID: 0e5193370cf5
Revises: 16b1014e4439
Create Date: 2025-07-23 17:05:50.740465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5193370cf5'
down_revision = '16b1014e4439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_url', sa.String(length=512), nullable=False))
        batch_op.drop_index('ix_file_map_short')
        batch_op.create_unique_constraint('uq_file_map_short', ['short'])
        batch_op.drop_column('ydisk_path')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('ydisk_path', sa.VARCHAR(length=1024), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_file_map_short', ['short'], unique=False)
        batch_op.drop_column('original_url')

    # ### end Alembic commands ###
